name: Deploy Portfolio
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt-get install -y sed
      - name: Inject GitHub Token
        run: sed -i 's/P_A_T/${{ secrets.GH_TOKEN }}/g' portfolio.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .

          
